Repository zzangmmz/zzimtory, pull requests merged in 2025-02, with the labels that each got.

#38 [feat] 주머니에 넣기 모달창 구현 완료 closes #37
  zzimtory/Model/Model.swift
  zzimtory/Search/DummyModel.swift
  zzimtory/Search/View/ItemCardsView/ItemCardContents.swift
  zzimtory/Search/View/ItemCardsView/ItemCardsView.swift
  zzimtory/Search/View/ItemCollectionView/ItemCollectionViewCell.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchView.swift
  zzimtory/Search/View/PocketSelectionView/AddNewPocketButton.swift
  zzimtory/Search/View/PocketSelectionView/PocketCollectionView+Cell.swift
  zzimtory/Search/View/PocketSelectionView/PocketSelectionInformLabel.swift
  zzimtory/Search/View/PocketSelectionView/PocketSelectionViewController.swift
Labels: enhancement

#35 [refactor] 구글, 네이버, 카카오 로그인 리팩토링
  zzimtory/App/AppDelegate.swift
  zzimtory/Helper/AuthProtocol.swift
  zzimtory/Helper/GoogleAuthManager.swift
  zzimtory/Helper/KakaoAuthManager.swift
  zzimtory/Helper/NaverAuthManager.swift
  zzimtory/Model/NaverUserModel.swift
  zzimtory/SnsLogin/LoginViewModel.swift
Labels: enhancement

#36 [feat] MainPocketView, PocketDetailView 구현
  .DS_Store
  zzimtory/App/Assets.xcassets/exampleImage.imageset/Contents.json
  zzimtory/App/Assets.xcassets/exampleImage.imageset/exOct.jpg
  zzimtory/App/ViewController.swift
  zzimtory/Main/MainPocketView/MainPocketViewModel.swift
  zzimtory/Main/MainPocketView/MainView.swift
  zzimtory/Main/MainPocketView/MainViewController.swift
  zzimtory/Main/MainPocketView/PocketCell.swift
  zzimtory/Main/PocketDetailView/PocketDetailView.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewController.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewModel.swift
  zzimtory/Model/Model.swift
Labels: enhancement

#40 [feat]PocketDetailView 서치바 구현 및 오버레이 뷰 추가
  .DS_Store
  .gitignore
  zzimtory/Helper/DatabaseManager.swift
  zzimtory/Helper/GoogleAuthManager.swift
  zzimtory/Helper/KakaoAuthManager.swift
  zzimtory/Helper/NaverAuthManager.swift
  zzimtory/Main/MainPocketView/MainPocketViewModel.swift
  zzimtory/Main/MainPocketView/MainView.swift
  zzimtory/Main/MainPocketView/MainViewController.swift
  zzimtory/Main/MainPocketView/PocketCell.swift
  zzimtory/Main/PocketDetailView/PocketDetailView.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewController.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewModel.swift
  zzimtory/Model/ItemModel.swift
  zzimtory/Model/UserModel.swift
  zzimtory/Search/View/PocketSelectionView/PocketCollectionView+Cell.swift
  zzimtory/Search/View/PocketSelectionView/PocketSelectionViewController.swift
  zzimtory/SnsLogin/LoginViewController.swift
  zzimtory/SnsLogin/LoginViewModel.swift
Labels: enhancement

#44 [feat] 메인뷰, 디테일뷰에 유저 주머니 데이터 바인딩
  zzimtory.xcodeproj/project.pbxproj
  zzimtory/App/Assets.xcassets/PocketBlack.imageset/Contents.json
  zzimtory/App/Assets.xcassets/PocketIcon/Contents.json
  zzimtory/App/Assets.xcassets/PocketIcon/EmptyPocketIcon.imageset/Contents.json
  zzimtory/App/Assets.xcassets/PocketIcon/EmptyPocketIcon.imageset/EmptyPocketIcon.png
  zzimtory/App/Assets.xcassets/PocketIcon/EmptyPocketIcon.imageset/EmptyPocketIcon@2x.png
  zzimtory/App/Assets.xcassets/PocketIcon/EmptyPocketIcon.imageset/EmptyPocketIcon@3x.png
  zzimtory/App/Assets.xcassets/PocketIcon/PocketBlack.imageset/Contents.json
  zzimtory/App/Assets.xcassets/PocketIcon/PocketBlack.imageset/제목_없는_아트워크 69 2.png
  zzimtory/App/Assets.xcassets/PocketIcon/PocketBlack.imageset/제목_없는_아트워크 69 2@2x.png
  zzimtory/App/Assets.xcassets/PocketIcon/PocketBlack.imageset/제목_없는_아트워크 69 2@3x.png
  zzimtory/App/Assets.xcassets/PocketIcon/PocketIcon.imageset/Contents.json
  zzimtory/App/Assets.xcassets/PocketIcon/PocketIcon.imageset/PocketIcon.png
  zzimtory/App/Assets.xcassets/PocketIcon/PocketIcon.imageset/PocketIcon@2x.png
  zzimtory/App/Assets.xcassets/PocketIcon/PocketIcon.imageset/PocketIcon@3x.png
  zzimtory/App/Assets.xcassets/exampleImage.imageset/Contents.json
  zzimtory/App/Assets.xcassets/exampleImage.imageset/exOct.jpg
  zzimtory/App/Assets.xcassets/logo.imageset/Contents.json
  zzimtory/App/Assets.xcassets/logo.imageset/image 5.png
  zzimtory/App/GoogleService-Info.plist
  zzimtory/App/Info.plist
  zzimtory/Detail/Model/DetailDummyItems.swift
  zzimtory/Detail/View/DetailView.swift
  zzimtory/Detail/View/DetailViewController.swift
  zzimtory/Detail/View/Extension/+String.swift
  zzimtory/Detail/View/Extension/+UIButton.swift
  zzimtory/Detail/View/ItemWebView.swift
  zzimtory/Detail/View/ItemWebViewController.swift
  zzimtory/Detail/View/TempItemCell.swift
  zzimtory/Detail/ViewModel/DetailViewModel.swift
  zzimtory/Helper/DatabaseManager.swift
  zzimtory/Main/MainPocketView/MainPocketViewModel.swift
  zzimtory/Main/MainPocketView/MainView.swift
  zzimtory/Main/MainPocketView/MainViewController.swift
  zzimtory/Main/MainPocketView/PocketCell.swift
  zzimtory/Main/PocketDetailView/PocketDetailView.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewController.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewModel.swift
  zzimtory/Model/UserModel.swift
  zzimtory/MyPage/MyPageViewController.swift
  zzimtory/MyPage/UserProfileView.swift
  zzimtory/Search/View/ItemCardsView/ItemCardOverlay.swift
  zzimtory/Search/View/ItemCardsView/ItemCardsView.swift
  zzimtory/Search/View/ItemCollectionView/ItemCollectionViewHeader.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchView.swift
  zzimtory/Search/View/PocketSelectionView/PocketCollectionView+Cell.swift
  zzimtory/Search/View/PocketSelectionView/PocketSelectionViewController.swift
  zzimtory/Tabbar/TabbarViewController.swift
  zzimtory/zzimtory.entitlements
Labels: enhancement

#46 [feat] 애플 로그인 구현
  zzimtory/Helper/AppleAuthManager.swift
  zzimtory/SnsLogin/LoginViewController.swift
  zzimtory/SnsLogin/LoginViewModel.swift
Labels: enhancement

#48 [feat] 기본적인 마이페이지 UI 구현 완료
  zzimtory/MyPage/MyPageViewController.swift
  zzimtory/MyPage/TermsOfService.swift
  zzimtory/MyPage/UserProfileView.swift
Labels: enhancement

#49 [feat] 주머니 상세 화면과 아이템 상세화면 연결 구현
  zzimtory/Main/MainPocketView/MainViewController.swift
  zzimtory/Main/PocketDetailView/PocketDetailView.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewController.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewModel.swift
Labels: enhancement

#51 [feat] 주머니, 아이템 정렬/검색 기능 구현, 편집 버튼 임시 삭제
  zzimtory.xcodeproj/project.pbxproj
  zzimtory/Main/MainPocketView/MainPocketViewModel.swift
  zzimtory/Main/MainPocketView/MainView.swift
  zzimtory/Main/MainPocketView/MainViewController.swift
  zzimtory/Main/MainPocketView/PocketCell.swift
  zzimtory/Main/PocketDetailView/PocketDetailView.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewController.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewModel.swift
Labels: enhancement

#52 전체 화면 연동 작업 closes #50
  zzimtory/App/SceneDelegate.swift
  zzimtory/Helper/DatabaseManager.swift
  zzimtory/MyPage/MyPageViewController.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchView.swift
  zzimtory/SnsLogin/LoginViewController.swift
  zzimtory/Tabbar/TabbarViewController.swift
Labels: bug, enhancement

#55 [hotfix] 로그아웃 상태 반영 안되는 이슈, 카드 스택 인덱스 에러, 디테일뷰 리로드 이슈 해결
  Base.lproj/LaunchScreen.storyboard
  zzimtory.xcodeproj/project.pbxproj
  zzimtory/App/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  zzimtory/App/Assets.xcassets/AppIcon.appiconset/Contents.json
  zzimtory/App/Assets.xcassets/LaunchIcon.imageset/Contents.json
  zzimtory/App/Assets.xcassets/LaunchIcon.imageset/LaunchIcon.svg
  zzimtory/App/Assets.xcassets/LaunchLogo.imageset/Contents.json
  zzimtory/App/Assets.xcassets/LaunchLogo.imageset/LaunchLogo.svg
  zzimtory/App/Assets.xcassets/LogoIcon.imageset/Contents.json
  zzimtory/App/Assets.xcassets/LogoIcon.imageset/LogoIcon.png
  zzimtory/App/Assets.xcassets/LogoIcon.imageset/LogoIcon@2x.png
  zzimtory/App/Assets.xcassets/LogoIcon.imageset/LogoIcon@3x.png
  zzimtory/App/Base.lproj/LaunchScreen.storyboard
  zzimtory/App/Info.plist
  zzimtory/App/ViewController.swift
  zzimtory/Detail/Model/DetailDummyItems.swift
  zzimtory/Detail/View/Extension/+UIImageView.swift
  zzimtory/Detail/ViewModel/DetailViewModel.swift
  zzimtory/Main/MainPocketView/MainPocketViewModel.swift
  zzimtory/Main/MainPocketView/MainView.swift
  zzimtory/Main/MainPocketView/MainViewController.swift
  zzimtory/Main/PocketDetailView/PocketDetailView.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewController.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewModel.swift
  zzimtory/Model/ItemModel.swift
  zzimtory/MyPage/MyPageViewController.swift
  zzimtory/Search/DummyModel.swift
  zzimtory/Search/View/ItemCardsView/ItemCardOverlay.swift
  zzimtory/Search/View/ItemCardsView/ItemCardsView.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchView.swift
  zzimtory/SnsLogin/LoginView.swift
  zzimtory/SnsLogin/LoginViewController.swift
  zzimtory/Tabbar/TabbarViewController.swift
Labels: bug

#71 [bug] 로그아웃 안되는 오류 해결, 네이버 자동로그인 오류 해결
  zzimtory/Helper/DatabaseManager.swift
  zzimtory/Helper/NaverAuthManager.swift
  zzimtory/MyPage/MyPageViewController.swift
Labels: bug

#74 [fix] 비로그인 상태에서 Tabbar 화면으로 진입되는 문제 해결
  zzimtory/App/SceneDelegate.swift
  zzimtory/SnsLogin/LoginViewController.swift
Labels: bug

#79 [hotfix] 비회원 플로우 중 MainViewController에서 주머니 추가 버튼 클릭 시 로그인 요구
  zzimtory/Main/MainPocketView/MainPocketViewModel.swift
  zzimtory/Main/MainPocketView/MainViewController.swift
  zzimtory/Main/MainPocketView/PocketCell.swift
  zzimtory/Model/SortOrder.swift
Labels: bug

#80 [feat] 비회원 로직 추가 (아이템 디테일 화면, 마이페이지)
  zzimtory/Detail/View/DetailViewController.swift
  zzimtory/Detail/View/ItemWebViewController.swift
  zzimtory/Main/MainPocketView/MainViewController.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewController.swift
  zzimtory/MyPage/MyPageViewController.swift
  zzimtory/MyPage/UserProfileView.swift
  zzimtory/SnsLogin/LoginViewController.swift
Labels: bug, enhancement

#81 [feat] 비회원 로직 구현 추가
  zzimtory/App/SceneDelegate.swift
  zzimtory/Detail/View/DetailViewController.swift
  zzimtory/Detail/View/ItemWebViewController.swift
  zzimtory/Main/MainPocketView/MainPocketViewModel.swift
  zzimtory/Main/MainPocketView/MainViewController.swift
  zzimtory/Main/MainPocketView/PocketCell.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewController.swift
  zzimtory/Model/SortOrder.swift
  zzimtory/MyPage/MyPageViewController.swift
  zzimtory/MyPage/UserProfileView.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchView.swift
  zzimtory/SnsLogin/LoginViewController.swift
Labels: enhancement

#89 [hotfix] 로그아웃 후에도 메인화면에 주머니가 남아있는 버그 해결
  zzimtory/App/Info.plist
  zzimtory/Detail/View/ButtonImageConstants.swift
  zzimtory/Detail/View/DetailView.swift
  zzimtory/Detail/View/DetailViewController.swift
  zzimtory/Detail/View/ItemWebView.swift
  zzimtory/Detail/View/ItemWebViewController.swift
  zzimtory/Detail/View/TempItemCell.swift
  zzimtory/Detail/ViewModel/DetailViewModel.swift
  zzimtory/Helper/DatabaseManager.swift
  zzimtory/Helper/KakaoAuthManager.swift
  zzimtory/Login/LoginButton.swift
  zzimtory/Login/LoginView.swift
  zzimtory/Login/LoginViewController.swift
  zzimtory/Login/LoginViewModel.swift
  zzimtory/SnsLogin/LoginButton.swift
Labels: bug

#100 [docs] 사용된 라이브러리에 Shuffle 추가
  README.md
Labels: documentation

#103 [refactor] 검색화면 UI 수정
  zzimtory/Detail/ItemDetailViewController.swift
  zzimtory/MyPage/RecentItemsView.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchHistoryTableCell.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchView.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchViewController.swift
  zzimtory/Search/View/ItemSearchView/SearchHistoryHeader.swift
  zzimtory/Search/ViewModel/ItemSearchViewModel.swift
Labels: refactoring

#105 [feat] 로그인 로딩화면 구현
  zzimtory/Helper/DatabaseManager.swift
  zzimtory/Login/LoginView.swift
  zzimtory/Login/LoginViewController.swift
  zzimtory/Main/MainPocketView/MainPocketViewModel.swift
  zzimtory/Main/MainPocketView/MainViewController.swift
Labels: bug

#106 [feat] 최근 본 아이템 저장 및 검색 화면과 아이템 상세 스크롤 화면 연결
  zzimtory/Detail/ItemDetailCollectionViewCell.swift
  zzimtory/Detail/ItemDetailViewController.swift
  zzimtory/Detail/ItemDetailViewModel.swift
  zzimtory/Detail/ItemDetailWebViewController.swift
  zzimtory/MyPage/MyPageViewController.swift
  zzimtory/MyPage/RecentItemCell.swift
  zzimtory/MyPage/RecentItemsView.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchViewController.swift
  zzimtory/Search/ViewModel/ItemSearchViewModel.swift
Labels: enhancement

#109 [feat] 카드스택 오버레이 작업 완료
  zzimtory/App/Assets.xcassets/SwipeGestureIcons/Contents.json
  zzimtory/App/Assets.xcassets/SwipeGestureIcons/swipeLeft.imageset/Contents.json
  zzimtory/App/Assets.xcassets/SwipeGestureIcons/swipeLeft.imageset/swipeLeftBlack900zt.png
  zzimtory/App/Assets.xcassets/SwipeGestureIcons/swipeLeft.imageset/swipeLeftWhite100zt.png
  zzimtory/App/Assets.xcassets/SwipeGestureIcons/swipeRight.imageset/Contents.json
  zzimtory/App/Assets.xcassets/SwipeGestureIcons/swipeRight.imageset/swipeRightBlack900zt.png
  zzimtory/App/Assets.xcassets/SwipeGestureIcons/swipeRight.imageset/swipeRightWhite100zt.png
  zzimtory/App/Assets.xcassets/SwipeGestureIcons/swipeUp.imageset/Contents.json
  zzimtory/App/Assets.xcassets/SwipeGestureIcons/swipeUp.imageset/swipeUpBlack900zt.png
  zzimtory/App/Assets.xcassets/SwipeGestureIcons/swipeUp.imageset/swipeUpWhite100zt.png
  zzimtory/Search/View/ItemCardsView/ItemCardOverlay.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchViewController.swift
Labels: enhancement

#111 [fix] 전체보기 주머니 DB에 저장해주는 코드 재 추가
  zzimtory/Main/MainPocketView/MainPocketViewModel.swift
Labels: bug

#112 [refactor] 검색 결과 무한 스크롤
  zzimtory/.swiftlint.yml
  zzimtory/Network/ShoppingAPI.swift
  zzimtory/Network/ShoppingRepository.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchViewController.swift
  zzimtory/Search/ViewModel/ItemSearchViewModel.swift
Labels: refactoring

#113 [feat] 메인화면과 아이템 상세화면 연결 및 아이템 상세화면 저장 버튼 버그 해결
  zzimtory/Detail/View/DetailView.swift
  zzimtory/Detail/View/DetailViewController.swift
  zzimtory/Detail/View/ItemDetailCollectionViewCell.swift
  zzimtory/Detail/View/ItemDetailViewController.swift
  zzimtory/Detail/View/ItemDetailWebView.swift
  zzimtory/Detail/View/ItemDetailWebViewController.swift
  zzimtory/Detail/View/ItemWebView.swift
  zzimtory/Detail/View/ItemWebViewController.swift
  zzimtory/Detail/ViewModel/DetailViewModel.swift
  zzimtory/Detail/ViewModel/ItemDetailViewModel.swift
  zzimtory/Detail/ViewModel/SimilarItemViewModel.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewController.swift
  zzimtory/MyPage/TermsOfServiceViewController.swift
Labels: bug, enhancement

#119 [feat] 검색결과 카드스택 다시 불러오기 버튼 생성
  zzimtory/Search/View/ItemCollectionView/ItemCollectionViewHeader.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchViewController.swift
Labels: enhancement

#121 [fix] 검색 화면 버그 수정 완료 closes #114
  zzimtory/Search/View/ItemSearchView/ItemSearchViewController.swift
  zzimtory/Search/ViewModel/ItemSearchViewModel.swift
Labels: bug

#123 [fix] 메인 화면, 메인 상세화면 그 외 자잘한 버그 수정했습니다!
  zzimtory/Detail/View/Extension/+Int.swift
  zzimtory/Detail/View/ItemDetailViewController.swift
  zzimtory/Detail/ViewModel/ItemDetailViewModel.swift
  zzimtory/Helper/AppleAuthManager.swift
  zzimtory/Helper/DatabaseManager.swift
  zzimtory/Helper/GoogleAuthManager.swift
  zzimtory/Helper/KakaoAuthManager.swift
  zzimtory/Helper/NaverAuthManager.swift
  zzimtory/Main/MainPocketView/MainPocketViewModel.swift
  zzimtory/Main/MainPocketView/MainView.swift
  zzimtory/Main/MainPocketView/MainViewController.swift
  zzimtory/Main/PocketDetailView/PocketDetailViewController.swift
  zzimtory/MyPage/MyPageViewController.swift
  zzimtory/MyPage/TermsOfServiceViewController.swift
  zzimtory/Search/View/ItemCollectionView/ItemCollectionView.swift
  zzimtory/Search/View/PocketSelectionView/PocketSelectionViewController.swift
Labels: bug

#124 [fix] 아이템 상세 화면 오토레이아웃 수정
  zzimtory/Detail/View/ItemDetailCollectionViewCell.swift
  zzimtory/Detail/View/ItemDetailViewController.swift
Labels: bug

#125 버그 수정, 리팩토링, 온보딩 기능 구현
  zzimtory/Search/View/ItemCardsView/ItemCardContents.swift
  zzimtory/Search/View/ItemCardsView/ItemCardOverlay.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchTutorial.swift
  zzimtory/Search/View/ItemSearchView/ItemSearchViewController.swift
Labels: bug, enhancement, refactoring
